name: Build and Deploy to Cloudflare

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Upload to Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js app
        run: yarn build

      - name: Build OpenNext bundle
        run: yarn opennextjs-cloudflare build

      - name: Upload to Cloudflare
        run: yarn opennextjs-cloudflare upload
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Deploy latest Worker version
        run: |
          VERSION_ID=$(npx wrangler versions list --json | jq -r 'sort_by(.created_at) | last(.[]).id')
          echo "Deploying version: $VERSION_ID"
          npx wrangler versions deploy --version-id $VERSION_ID --yes
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}